# streamlit run app.py

import streamlit as st
import pickle
import pandas as pd
import yfinance as yf
import numpy as np
import joblib
import sklearn
import matplotlib.pyplot as plt
from pandas_datareader.data import DataReader
from datetime import datetime, timedelta
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

# -----------------------
# DATA FETCH FUNCTIONS  (moved outside run_pipeline so they can be reused)
# -----------------------
def fetch_gold(start, end):
    df = yf.download("GC=F", start=start, end=end + timedelta(days=1),
                     interval="1d", auto_adjust=False, progress=False).dropna()
    df = df.reset_index()
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df[["Date","High","Low","Open","Volume","Close"]].rename(columns={"Close":"Gold_Price"})

def fetch_brent(start, end):
    df = yf.download("BZ=F", start=start, end=end + timedelta(days=1),
                     interval="1d", progress=False, auto_adjust=False).dropna()
    df = df.reset_index()
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df[["Date","Close"]].rename(columns={"Close":"Brent_Price"})

def fetch_dxy(start, end):
    df = yf.download("DX-Y.NYB", start=start, end=end + timedelta(days=1),
                     interval="1d", auto_adjust=False, progress=False).dropna()
    df = df.reset_index()
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df[["Date","Close"]].rename(columns={"Close":"DXY_Price"})

def fetch_fed(start, end):
    df = DataReader("EFFR","fred", start, end).reset_index().rename(columns={"DATE":"Date","EFFR":"Fed_Rate"})
    df["Date"] = pd.to_datetime(df["Date"])
    daily_index = pd.date_range(start, end, freq="D")
    df = df.set_index("Date").reindex(daily_index).ffill().reset_index().rename(columns={"index":"Date"})
    return df

def merge_features(gold, brent, dxy, fed):
    df = gold.merge(brent, on="Date", how="left")\
             .merge(dxy, on="Date", how="left")\
             .merge(fed, on="Date", how="left")
    df[["Brent_Price","DXY_Price","Fed_Rate"]] = df[["Brent_Price","DXY_Price","Fed_Rate"]].ffill().bfill()
    df[["High","Low","Open","Volume","Gold_Price"]] = df[["High","Low","Open","Volume","Gold_Price"]].interpolate()
    return df.dropna(subset=["High","Low","Open","Volume"]).sort_values("Date")

def next_trading_day(date):
    d = date + timedelta(days=1)
    while d.weekday() >= 5:
        d += timedelta(days=1)
    return d

# --- FULL PIPELINE FUNCTION ---
def run_pipeline():
    feature_cols = ["High","Low","Open","Volume","Brent_Price","DXY_Price","Fed_Rate"]

    # -----------------------
    # LOAD PIPELINE
    # -----------------------
    # Load pipeline — it must be generated by the notebook first
    try:
        pipeline = joblib.load("sgd_pipeline.pkl")
    except FileNotFoundError:
        st.error("❌ sgd_pipeline.pkl not found. Please run Gold_Data_analysis_2.ipynb first to train and save the pipeline.")
        st.stop()

    # VERSION GUARD: sklearn version mismatch causes partial_fit to explode coefficients.
    # If version changed, the user must re-run the notebook with the current sklearn version.
    stored_ver = getattr(pipeline, "sklearn_version", None)
    if stored_ver != sklearn.__version__:
        st.error(f"❌ sklearn version mismatch: pipeline was trained with {stored_ver} but you are running {sklearn.__version__}. Please re-run Gold_Data_analysis_2.ipynb to retrain and save a new sgd_pipeline.pkl.")
        st.stop()

    pipeline.last_train_date = getattr(pipeline, "last_train_date", datetime(2025, 11, 30).date())
    pipeline.last_fed_rate   = getattr(pipeline, "last_fed_rate", None)

    today     = datetime.today().date()
    yesterday = today - timedelta(days=1)

    # -----------------------
    # ONLINE LEARNING
    # Two-tier update strategy:
    #
    # DAILY  — SGD partial_fit only, scaler stays fixed.
    #          Safe for small batches (1-5 rows). Keeps model current.
    #
    # MONTHLY — When 30+ new days have accumulated since the last scaler
    #           update, also update the scaler with the full batch.
    #           Safe because batch is large enough to give stable statistics.
    #           This prevents long-term drift as gold prices move to new ranges.
    # -----------------------
    if pipeline.last_train_date >= yesterday:
        st.info("📌 Model already updated for today. Skipping online learning.")
    else:
        learn_start  = pipeline.last_train_date + timedelta(days=1)
        df_temp_gold = fetch_gold(learn_start, yesterday)
        learn_end    = None if df_temp_gold.empty else df_temp_gold["Date"].max().date()

        if learn_end is not None and learn_start <= learn_end:
            df_learn = merge_features(fetch_gold(learn_start, learn_end),
                                      fetch_brent(learn_start, learn_end),
                                      fetch_dxy(learn_start, learn_end),
                                      fetch_fed(learn_start, learn_end))
            if pipeline.last_fed_rate is not None:
                df_learn["Fed_Rate"] = df_learn["Fed_Rate"].fillna(pipeline.last_fed_rate)
            df_learn_complete = df_learn.dropna(subset=feature_cols)

            if not df_learn_complete.empty:
                X_new = df_learn_complete[feature_cols].values
                y_new = df_learn_complete["Gold_Price"].values
                days_of_new_data = len(df_learn_complete)

                # --- MAPE-weighted sample weights ---
                # High MAPE → model uncertain → learn aggressively
                # Low MAPE  → model confident → learn conservatively
                try:
                    _eval_start = pipeline.last_train_date - timedelta(days=60)
                    _df_eval = merge_features(
                        fetch_gold(_eval_start, pipeline.last_train_date),
                        fetch_brent(_eval_start, pipeline.last_train_date),
                        fetch_dxy(_eval_start, pipeline.last_train_date),
                        fetch_fed(_eval_start, pipeline.last_train_date)
                    ).dropna(subset=feature_cols + ["Gold_Price"])
                    _current_mape = mean_absolute_percentage_error(
                        _df_eval["Gold_Price"],
                        pipeline.predict(_df_eval[feature_cols])
                    ) * 100
                    # MAPE 0.5% → weight 0.5 | MAPE 5% → weight 1.0 | MAPE 20% → weight 3.0
                    _weight = float(np.clip(_current_mape / 5.0, 0.5, 3.0))
                except Exception:
                    _weight = 1.0
                _sample_weights = np.full(len(y_new), _weight)

                # --- MONTHLY scaler update (30+ days accumulated) ---
                # Calling partial_fit on a large batch is safe — it accumulates
                # the running mean/std correctly and keeps the scaler calibrated
                # as gold prices move to new ranges over time.
                # Calling it on tiny daily batches (3-5 rows) is what causes explosion.
                last_scaler_update = getattr(pipeline, "last_scaler_update", pipeline.last_train_date)
                days_since_scaler_update = (learn_end - last_scaler_update).days

                if days_since_scaler_update >= 30:
                    pipeline.named_steps["scaler"].partial_fit(X_new)
                    pipeline.last_scaler_update = learn_end

                # --- DAILY SGD update (always) ---
                X_scaled = pipeline.named_steps["scaler"].transform(X_new)
                pipeline.named_steps["sgd"].partial_fit(X_scaled, y_new,
                                                        sample_weight=_sample_weights)

                pipeline.last_train_date  = df_learn_complete["Date"].max().date()
                pipeline.last_fed_rate    = float(df_learn_complete["Fed_Rate"].iloc[-1])
                pipeline.sklearn_version  = sklearn.__version__
                joblib.dump(pipeline, "sgd_pipeline.pkl")

    # -----------------------
    # NEXT-DAY PREDICTION
    # -----------------------
    df_pred = merge_features(fetch_gold(pipeline.last_train_date - timedelta(days=10), pipeline.last_train_date),
                             fetch_brent(pipeline.last_train_date - timedelta(days=10), pipeline.last_train_date),
                             fetch_dxy(pipeline.last_train_date - timedelta(days=10), pipeline.last_train_date),
                             fetch_fed(pipeline.last_train_date - timedelta(days=10), pipeline.last_train_date))
    df_pred       = df_pred.dropna(subset=feature_cols)
    last_row      = df_pred.iloc[-1]
    next_date     = next_trading_day(last_row["Date"].date())
    X_pred_df     = pd.DataFrame([last_row[feature_cols]], columns=feature_cols)
    predicted_price = pipeline.predict(X_pred_df)[0]

    # -----------------------
    # EVALUATION — compute MAE and MAPE on full evaluation window
    # -----------------------
    start_date = datetime(2024, 11, 30).date()
    end_date   = pipeline.last_train_date
    df_show = merge_features(fetch_gold(start_date, end_date),
                             fetch_brent(start_date, end_date),
                             fetch_dxy(start_date, end_date),
                             fetch_fed(start_date, end_date))
    df_show = df_show.dropna(subset=feature_cols + ["Gold_Price"]).reset_index(drop=True)
    df_show["Predicted"] = pipeline.predict(df_show[feature_cols])

    mae  = mean_absolute_error(df_show["Gold_Price"], df_show["Predicted"])
    mape = mean_absolute_percentage_error(df_show["Gold_Price"], df_show["Predicted"]) * 100

    # Save results to pickle
    data_to_save = {
        "df_show":           df_show,
        "next_day_price":    predicted_price,
        "prediction_date":   next_date,
        "last_trained_date": pipeline.last_train_date,
        "mae":               mae,
        "mape":              mape,
    }
    with open("gold_data_all.pkl", "wb") as f:
        pickle.dump(data_to_save, f)

    return df_show, predicted_price, next_date, pipeline.last_train_date, mae, mape

# -----------------------
# STREAMLIT APP
# -----------------------
st.title("📈 Gold Price Prediction System")

# -----------------------
# AUTO-RUN ONCE DAILY
# Uses session_state to track whether the pipeline already ran today.
# On the first load of any new day it runs automatically.
# The manual Update button forces a re-run regardless.
# -----------------------
today_str = datetime.today().strftime("%Y-%m-%d")
already_ran_today = st.session_state.get("last_run_date") == today_str

if st.button("🔄 Update") or not already_ran_today:
    with st.spinner("Running pipeline, please wait..."):
        df_show, predicted_price, next_date, last_trained_date, mae, mape = run_pipeline()
    st.session_state["last_run_date"] = today_str

else:
    # Pipeline already ran today — load saved results
    _loaded_ok = False
    try:
        with open("gold_data_all.pkl", "rb") as f:
            data = pickle.load(f)
        df_show           = data["df_show"]
        predicted_price   = data["next_day_price"]
        next_date         = data["prediction_date"]
        last_trained_date = data["last_trained_date"]
        mae               = data.get("mae",  None)
        mape              = data.get("mape", None)
        _loaded_ok = True
    except Exception:
        pass

    # Sanity check: predictions outside $1,000–$15,000 means corrupted pkl
    if _loaded_ok:
        try:
            if not (1000 < data["next_day_price"] < 15000):
                _loaded_ok = False
        except Exception:
            _loaded_ok = False

    if not _loaded_ok:
        import os
        # Only delete the data cache, not the pipeline
        try: os.remove("gold_data_all.pkl")
        except: pass
        with st.spinner("Running pipeline, please wait..."):
            df_show, predicted_price, next_date, last_trained_date, mae, mape = run_pipeline()
        st.session_state["last_run_date"] = today_str

# Show last trained date
st.info(f"🛠️ Model last trained up to: {last_trained_date}")

# Show next-day prediction
st.subheader("🔮 Next-Day Prediction")
st.success(f"Predicted Gold Price for {next_date}: ${predicted_price:.2f}")

# Show MAE / MAPE metrics
st.subheader("📐 Model Accuracy")
if mae is not None and mape is not None:
    col1, col2 = st.columns(2)
    col1.metric(
        label="MAE — Mean Absolute Error",
        value=f"${mae:.2f}",
        help="Average dollar difference between predicted and actual price. Lower is better."
    )
    col2.metric(
        label="MAPE — Mean Absolute Percentage Error",
        value=f"{mape:.2f}%",
        help="Average % error. Under 1% = excellent. Used to adjust online learning weight."
    )
    # Confidence interpretation
    if mape < 1.0:
        st.success(f"✅ Model confidence: HIGH — MAPE {mape:.2f}% (online learning weight: conservative)")
    elif mape < 3.0:
        st.warning(f"⚠️ Model confidence: MODERATE — MAPE {mape:.2f}% (online learning weight: normal)")
    else:
        st.error(f"❌ Model confidence: LOW — MAPE {mape:.2f}% (online learning weight: aggressive)")
else:
    st.info("ℹ️ Press Update to compute accuracy metrics.")

# Show Actual vs Predicted chart (from 30/11/2024)
start_plot_date = pd.to_datetime("2024-11-30")
df_plot = df_show[df_show["Date"] >= start_plot_date].copy()
df_plot["Date"] = pd.to_datetime(df_plot["Date"])

st.subheader("📊 Actual vs Predicted")
st.line_chart(df_plot.set_index("Date")[["Gold_Price", "Predicted"]])